# Notes

Put your homework in the directory with your name. Please mentionin this file the names of any students with whom you collaborated. If you didn't collaborate with anyone, mark your collaborators as "None." 
Remember, your goal is to communicate. Full credit will be given only to correct solutions which are described clearly. Convoluted and obtuse descriptions will receive low marks. 
To complete your homework, you may ONLY consult the following material: 
1.	lecture slides
2.	course notes you or others took during lecture.
3.	the required text (CLRS)
4.	websites that may clarify the concepts covered in the material but do not in any way provide complete solutions to the problems.

Deadline 2/20/2019

Please provide an answer to the following questions: 

# Question 1 (10 pts)

Create a script that: 
1. load the iris data.
2. scale the indipendent features.
3. compute the correlation coefficients and co-variance among all the pair of indipendent features.
4. compute the PCA and show the principal components (their coefficients) 
5. compute the correlation coefficient between each original feature and the new features generated by the PCA 


In [119]:
import pandas as pd
import numpy as np
import math
from sklearn import preprocessing
from sklearn.decomposition import PCA

In [92]:
#1. load the iris data
filename = "iris.csv"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
data_iris = pd.read_csv(filename, names=names)
data_iris.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [93]:
#2. scale the independent features.
X = data_iris.iloc[:,0:4]
X_scaled = preprocessing.scale(X)

In [94]:
#3. compute the correlation coefficients and co-variance among all the pair of independent features.
np.corrcoef(X.T)

array([[ 1.        , -0.10936925,  0.87175416,  0.81795363],
       [-0.10936925,  1.        , -0.4205161 , -0.35654409],
       [ 0.87175416, -0.4205161 ,  1.        ,  0.9627571 ],
       [ 0.81795363, -0.35654409,  0.9627571 ,  1.        ]])

In [95]:
np.cov(X.T)

array([[ 0.68569351, -0.03926846,  1.27368233,  0.5169038 ],
       [-0.03926846,  0.18800403, -0.32171275, -0.11798121],
       [ 1.27368233, -0.32171275,  3.11317942,  1.29638747],
       [ 0.5169038 , -0.11798121,  1.29638747,  0.58241432]])

In [96]:
#4. compute the PCA and show the principal components (their coefficients) 
PCA_model = PCA(n_components=4)
PC_PCA = PCA_model.fit(X_scaled)
PC_PCA.components_

array([[ 0.52237162, -0.26335492,  0.58125401,  0.56561105],
       [ 0.37231836,  0.92555649,  0.02109478,  0.06541577],
       [-0.72101681,  0.24203288,  0.14089226,  0.6338014 ],
       [-0.26199559,  0.12413481,  0.80115427, -0.52354627]])

In [97]:
#5 compute the correlation coefficient between each original feature and the new features generated by the PCA 
X_PCA = PC_PCA.transform(X_scaled)
new_old_comp = pd.DataFrame(np.corrcoef(X_PCA.T, X.T)).iloc[0:4,4:8]
new_old_comp.columns = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width']
new_old_comp.index = ['PC1', 'PC2', 'PC3', 'PC4']
new_old_comp

sepal-length  sepal-width  petal-length  petal-width
PC1      0.891224    -0.449313      0.991684     0.964996
PC2      0.357352     0.888351      0.020247     0.062786
PC3     -0.276774     0.092908      0.054084     0.243295
PC4     -0.037610     0.017820      0.115009    -0.075157

# Question 2 (5 pts + (5 pts Extra))

#Edoardo you did not connect the correlation with the eigenvector coefficient. 3pts

1. What you can observe by comparing the results in Question1 of the point 4 and 5?
2. Can you define any property?
3. If there is any property are you able to formally prove it? (5 extra pts)


In [130]:
# The proportion of variance from the original features
vars = X.apply(lambda x : np.var(x))
(vars/sum(vars)) * 100

sepal-length    15.006562
sepal-width      4.114512
petal-length    68.132654
petal-width     12.746273
dtype: float64

In [136]:
# The proportion of variance from the projected features from PCA
vars = pd.DataFrame(X_PCA).apply(lambda x : np.var(x))
(vars/sum(vars)) * 100

0    72.770452
1    23.030523
2     3.683832
3     0.515193
dtype: float64

In [137]:
print(PCA_model.explained_variance_)
print(PCA_model.explained_variance_ratio_)
print(PCA_model.explained_variance_ratio_.cumsum())

[2.93035378 0.92740362 0.14834223 0.02074601]
[0.72770452 0.23030523 0.03683832 0.00515193]
[0.72770452 0.95800975 0.99484807 1.        ]


* From point 3 in question 1, we can observe that the variables sepal-length, petal-length and petal-width are highly correlated with each other. 
* From point 5, we observe that these variables are highly correlated with the first projected feature from the PCA. 
* From the above computation, we observe that these 3 variables captures the most variability in the original feature space. 
* Hence, we can say that the first Principle Component is the linear combination of these variables since they capture the most variability of all possible linear combinations.
* From point 4 we see that the variables sepal-length, petal-length and petal-width all load on the SAME Principal Component (Eigenvector) which is the first component. And the variable sepal-width loads on a different Principal Component (Eigenvector)

#### 2 Can you define any property?

* (i) Independent - (The new features are independent).
* (ii) Communality - A measure of how well the principal components explain the variance of each of the variables. This is the square of the correlation of the original variable with the new feature, this gives the part of the variance accounted for by the new feature. The sum of these squares is the explained variance for the original features. 

#### If there is any property are you able to formally prove it? (5 extra pts)

# Question 3 (10 pts)

1) Write a code in pure python (Numpy and Scipy are allowed, do not use scikit) able to create a decision tree. In input, you should provide the independent features and the dependent feature (the class) separately.
You can assume the dependent features and the independent feature binary. Please implements the Gini index and the entropy gain ratio. You can read the code available online, but you cannot plagiarize it.

2) Create a toy example to run and test your code (please show the result).



In [99]:
leaf_node_MIN = 5
tree_depth_MAX = 10
target_Attribute = 'class' # Should be updated for a new dataset

In [111]:
def print_tree(tree, tree_depth = 0, node=""):
    if tree.isleafNode:
        print("Tree Depth - " + str(tree_depth), "{{leaf}} label: %s, leaf-shape: %s" % (tree.leafLabel, str(tree.train.shape)))
        print("---------------")
        
    else:
       print( "  " * tree_depth + "- " + "[[node]] shape %s, [[split_Attribute]]: %s, [[split_Break/value]]: %s" % (str(tree.train.shape), tree.splitAttr, tree.splitBreak))
       print_tree(tree.left_node, tree_depth + 1, "left")
       print_tree(tree.right_node, tree_depth + 1, "right")


In [140]:
class DecisionTree:
    # Note: Dependent and Independent features are Binary
    # Input 1 for Gini index
    print("for Gain Ratio, use measure = 2, for gini-index, measure = 1") 
    Node_count = 0
    def __init__(self, train, target, tree_depth=0, measure = 1):
        DecisionTree.Node_count += 1
        self.isleafNode = False
        self.Impurity_measue = measure
        self.train = train
        
        self.leafLabel = train[target].value_counts().index[0]
        # Stopping Criteria - Terminates the Tree growing process
        # (1)-Check whether all the instances have identical class label or attribute values
        if len(train[target].value_counts())==1:
            self.isleafNode = True
            return
    
        # (2)-Check if the thresholds for leaf node instances or Tree depth are reached(This prevents data fragmentation)
        if len(train) <= leaf_node_MIN or tree_depth > tree_depth_MAX:
            self.isleafNode = True
            return
        
        self.objBestFit = self.find_best_split(train, target, measure)   # find_best split attribute and value
        self.splitAttr = list(self.objBestFit.index)[0]   # get spliting attribute
        self.splitBreak = list(self.objBestFit[0].keys())[0]   # get best break(value) of the spliting attribute
        # Split tree node
        idx = train[self.splitAttr]==self.splitBreak
        self.left_split = train[idx]
        self.right_split = train[~idx]
        self.left_node = DecisionTree(self.left_split, target, tree_depth+1, measure)
        self.right_node = DecisionTree(self.right_split, target, tree_depth+1, measure)
        
    # Compute the weighted impurity measure for the children nodes and calculate the gain
    def impurity_measure(self, attribute,target,train,I_parent,measure):
        N = len(attribute)  # Size of parent
                
        I_table = pd.crosstab(train.loc[:,target],attribute)
        colnames = list(I_table.columns)
        dict_Gain_val = dict()  # data structure to store the gain in purity 

        # Produce only binary splits 
        # To keep it simple, instead of considering all 2^(k-1)-1 ways of creating binary partition
        # We consider k ways for test conditions that produce more than 2 way splits
        # For example an attribute with 3 splits (A,B,C), we would consider A & BC; B & AC; C & AB
        k = np.where(len(colnames)==2,1,len(colnames)).item()

        if measure == 1: # Gini Index measure of impurity
            Gini_vals = pd.Series()
            for i in range(k):
               n1class = sum(I_table.loc[:,colnames[i]])      # Total instances in class n1
               node_1 = I_table.loc[:,colnames[i]]/n1class    # fraction of instances that belong to node-1(n1): pi=ni/N1class
               p1 = node_1.iloc[0]
               p2 = node_1.iloc[1]
               I_node1 = 2*p1*p2   #calculate node 1 impurity: 2*p1*p2 = 1-p1^2-p2^2
               n2class = sum(I_table.loc[:, ~I_table.columns.isin([colnames[i]])].sum(1))   # Total instances in class ~n1
               
               # Avoid division by zero
               if n2class == 0:
                     I_weight = (n1class/N * I_node1)
                     Gini_vals = Gini_vals.append(pd.Series(I_weight, index=[colnames[i]]))
                     continue
    
               node_2 = I_table.loc[:, ~I_table.columns.isin([colnames[i]])].sum(1)/n2class # fraction of instances in split ~n1: pi=ni/N2class
               p1 = node_2.iloc[0]
               p2 = node_2.iloc[1]
               I_node2  = 2*p1*p2   #calculate node 2 impurity: 2*p1*p2 = 1-p1^2-p2^2
               I_weight = (n1class/N * I_node1) + (n2class/N * I_node2)  #weighted sum of impurities of the child nodes(I_node1, I_node2)
               Gini_vals = Gini_vals.append(pd.Series(I_weight, index=[colnames[i]])) #Store the weighted gini-index for all child node
    
            Gain = I_parent - Gini_vals.loc[Gini_vals.idxmin()]  #return the minimum weighted impurity measure (occurs if an attribute has more than 2 branches)
                                                                                              #and subtract from the parent impurity measure   
            dict_Gain_val[Gini_vals.idxmin()] = Gain  
        else: #Entropy Gain Ratio
            Entropy_vals = pd.Series()
            for i in range(k):
               n1class = sum(I_table.loc[:,colnames[i]])      # Total instances in class n1
               node_1 = I_table.loc[:,colnames[i]]/n1class    # fraction of instances that belong to node-1(n1): pi=ni/N1class
               p1 = node_1.iloc[0]
               p2 = node_1.iloc[1]
               
               #Avoid taking the log of zero
               p1 = np.nan if p1 == 0 else p1
               p2 = np.nan if p2 == 0 else p2
               
               p1i = -p1*math.log2(p1)
               p1i = 0 if np.isnan(p1i) else p1i
               p2i = -p1*math.log2(p1)
               p2i = 0 if np.isnan(p2i) else p2i
               #I_node1 = -p1*math.log2(p1)-p2*math.log2(p2)   #calculate Entropy for node 1: -p1log(p1)-p2log(p2)
               I_node1 = p1i + p2i
               
               n2class = sum(I_table.loc[:, ~I_table.columns.isin([colnames[i]])].sum(1))   # Total instances in class ~n1
               # Avoid division by zero
               if n2class == 0:
                     I_weight = (n1class/N * I_node1)
                     Gain_Ratio = (I_parent - I_weight)/-(n1class/N)*math.log2(n1class/N) 
                     Entropy_vals = Entropy_vals.append(pd.Series(Gain_Ratio, index=[colnames[i]]))
                     continue
            
               node_2 = I_table.loc[:, ~I_table.columns.isin([colnames[i]])].sum(1)/n2class # fraction of instances in split ~n1: pi=ni/N2class
               p1 = node_2.iloc[0]
               p2 = node_2.iloc[1]
               #Avoid taking the log of zero
               p1 = np.nan if p1 == 0 else p1
               p2 = np.nan if p2 == 0 else p2
 
               p1i = -p1*math.log2(p1)
               p1i = 0 if np.isnan(p1i) else p1i
               p2i = -p1*math.log2(p1)
               p2i = 0 if np.isnan(p2i) else p2i              
               #I_node2  = -p1*math.log2(p1)-p2*math.log2(p2)   #calculate Entropy for node 2: -p1log(p1)-p2log(p2)
               I_node2 = p1i + p2i
               
               I_weight = (n1class/N * I_node1) + (n2class/N * I_node2)  #weighted sum of impurities of the child nodes(I_node1, I_node2)
               Gain_Ratio = (I_parent - I_weight)/-(n1class/N)*math.log2(n1class/N) - (n2class/N)*math.log2(n2class/N)
               Entropy_vals = Entropy_vals.append(pd.Series(Gain_Ratio, index=[colnames[i]])) 
               
            dict_Gain_val[Entropy_vals.idxmax()] = Gain_Ratio
        return dict_Gain_val
         
    # Determine the attribute test condition for partitioning the training instances associated with a node
    def find_best_split(self, train, target, measure):
        # get the impurity measure for the parent node
        class_count = train[target].value_counts()   # class distribution at parent node 
        p1 = class_count[0]/sum(class_count)
        p2 = class_count[1]/sum(class_count)

        if measure == 1: # Gini Index measure of impurity
            # Gini index of parent node before splitting
            I_parent  = 2*p1*p2   
            # get the impurity measure for each child node
            gini_indices = train.loc[:,~train.columns.isin([target])].apply(self.impurity_measure, axis=0, args=(target,train,I_parent,measure,))
            optimal_val = max([ix for ix in gini_indices], key=lambda x:x[list(x.keys())[0]])
            return gini_indices[gini_indices==optimal_val]            
        else:  #Entropy Gain Ratio 
            # Parent Entropy before splitting 
            I_parent = -p1*math.log2(p1)-p2*math.log2(p2)
            # get the impurity measure(gain ratio) for each attribute
            gain_Ratios = train.loc[:,~train.columns.isin([target])].apply(self.impurity_measure, axis=0, args=(target,train,I_parent,measure,))
            optimal_val = max([ix for ix in gain_Ratios], key=lambda x:x[list(x.keys())[0]])
            return gain_Ratios[gain_Ratios==optimal_val]            

for Gain Ratio, use measure = 2, for gini-index, measure = 1


In [141]:
filename = "breast-cancer.data"
names = ['class','age','menopause','tumor_size','inv_nodes','node_caps','deg-malig','breast','breast_quad','irradiat']
dataset = pd.read_csv(filename, names=names)
tree = DecisionTree(dataset, target_Attribute,measure=2)
print_tree(tree)

- [[node]] shape (286, 10), [[split_Attribute]]: age, [[split_Break/value]]: 20-29
Tree Depth - 1 {{leaf}} label: no-recurrence-events, leaf-shape: (1, 10)
---------------
  - [[node]] shape (285, 10), [[split_Attribute]]: age, [[split_Break/value]]: 70-79
    - [[node]] shape (6, 10), [[split_Attribute]]: node_caps, [[split_Break/value]]: ?
Tree Depth - 3 {{leaf}} label: recurrence-events, leaf-shape: (1, 10)
---------------
Tree Depth - 3 {{leaf}} label: no-recurrence-events, leaf-shape: (5, 10)
---------------
    - [[node]] shape (279, 10), [[split_Attribute]]: tumor_size, [[split_Break/value]]: 45-49
Tree Depth - 3 {{leaf}} label: no-recurrence-events, leaf-shape: (3, 10)
---------------
      - [[node]] shape (276, 10), [[split_Attribute]]: tumor_size, [[split_Break/value]]: 5-9
Tree Depth - 4 {{leaf}} label: no-recurrence-events, leaf-shape: (4, 10)
---------------
        - [[node]] shape (272, 10), [[split_Attribute]]: tumor_size, [[split_Break/value]]: 0-4
          - [[node]

### Please Note: Trying to print the subset of the dataset at every node made the tree very unreadable. Hence, I removed it and displayed the shape of the node instead.